# Stratum 1 servers for the eessi.io domain
CVMFS_SERVER_URL="http://aws-eu-central-s1.eessi.science/cvmfs/@fqrn@;http://azure-us-east-s1.eessi.science/cvmfs/@fqrn@"

# Public keys for the eessi.io domain
CVMFS_KEYS_DIR="/etc/cvmfs/keys/eessi.io"

# Enable or disable the Geo API, based on the configuration file
CVMFS_USE_GEOAPI="yes"

# The client profile is supposed to be set in /etc/cvmfs/default.local
if [ "$CVMFS_CLIENT_PROFILE" = "single" ]; then
  if [ "$CVMFS_HTTP_PROXY" = "" ]; then
    # For individual clients (laptops, clusters < 5 nodes), use a site proxy
    # where possible and otherwise a direct stratum 1 connection
    CVMFS_HTTP_PROXY="DIRECT"
  fi
fi
