# documentation: https://help.github.com/en/articles/workflow-syntax-for-github-actions
name: Tests for scripts
on:
  push:
    paths:
      - scripts/sign_verify_file_ssh.sh
  pull_request:
    paths:
      - scripts/sign_verify_file_ssh.sh
permissions:
  contents: read # to fetch code (actions/checkout)
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - name: checkout
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

    - name: test sign_verify_file_ssh.sh script
      run: |
          # Create a PEM format ssh identity
          ssh-keygen -t rsa -b 4096 -m PEM -f id_rsa.pem -N ""
          # Create a file to sign
          echo "Very important stuff" > out.txt
          export FILE_TO_SIGN="out.txt"
          # Sign the file
          ./scripts/sign_verify_file_ssh.sh sign id_rsa.pem "$FILE_TO_SIGN"
          # Create an allowed_signers file based on the public key
          echo -n "allowed_identity " > allowed_signers
          cat id_rsa.pem.pub >> allowed_signers
          # Verify the signature
          ./scripts/sign_verify_file_ssh.sh verify allowed_signers "$FILE_TO_SIGN"
          # Make a new signature that does not appear in the allowed signers file
          ssh-keygen -t rsa -b 4096 -m PEM -f id_rsa.alt.pem -N ""
          # Replace the allowed signers file
          echo -n "disallowed_identity " > allowed_signers
          cat id_rsa.alt.pem.pub >> allowed_signers
          # Make sure signature checking fails in this case
          ./scripts/sign_verify_file_ssh.sh verify allowed_signers "$FILE_TO_SIGN" && exit 1 || echo "Expected failure for unknown identity"
